controller_list:
  - name: fake_panda_arm_1_controller
    type: $(arg execution_type)
    joints:
      - panda_1_joint1
      - panda_1_joint2
      - panda_1_joint3
      - panda_1_joint4
      - panda_1_joint5
      - panda_1_joint6
      - panda_1_joint7
  - name: fake_panda_arm_2_controller
    type: $(arg execution_type)
    joints:
      - panda_2_joint1
      - panda_2_joint2
      - panda_2_joint3
      - panda_2_joint4
      - panda_2_joint5
      - panda_2_joint6
      - panda_2_joint7
initial:  # Define initial robot poses.
#  - group: panda_arm_1
#    pose: home

  []